### ISSUE TITLE
[Bug]: pipenv install error

### ISSUE THREAD

**Issue by DimitarTsonov** [LeagueOfPoro/CapsuleFarmerEvolved#143]
### What happened?

I followed the installation guide for linux, but got the following error when trier to install virtual environment:

AttributeError: module 'collections' has no attribute 'MutableMapping'

### What should happen?

Virtual environment should be installed with success.

### Capsule Farmer Version

v1.3

### Operating System

Other (Non Windows are not natively supported)

### Operating System Version

Ubuntu LTS 22.04
amd64(x86)

### Relevant log output

```shell
ubuntu@ip-172-31-20-135:~/CapsuleFarmerEvolved$ pipenv install
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 347, in install
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

### Notes

pipenv install ran successfully on Ubuntu LTS 22.04 x64(Arm)

Python version 3.10.6

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by LeagueOfPoro** [comment]
Try to update your `setuptools` via pip/pipenv.

**Comment by DimitarTsonov** [comment]
Got it working.

Since I am trying to get it working with ec2 instance.
Steps:
1. sudo apt update
2. sudo apt-get install python3-pip
3. pip install pipenv
But don't know why    pipenv install  is not recognized as command 
Command 'pipenv' not found, but can be installed with:
sudo apt install pipenv
4. sudo apt install pipenv
5. pipenv install

Looks like if I install pipenv via "sudo apt install pipenv" before I install pipenv with "pip install pipenv" the error occurs.

**Comment by auroraisluna** [comment]
Because pipenv should not be installed via apt. Command is not recognized because its probably not in your path. Running `python -m pipenv` would most likely allow you to run the command, or properly setting your path.

**Comment by DimitarTsonov** [comment]
I think you're right @auroraisluna.
Thanks :)
This topic may be useful for people trying to run the farmer for free in AWS EC2 instance and facing the same issue.
