### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WenseRainy** [LeagueOfPoro/CapsuleFarmerEvolved#148]
### What happened?

I used the vpn service, and the software I used was clash, but it still displayed an error. The following is the log table recorded by the software, please help me to check.

![微信截图_20230215201940](https://user-images.githubusercontent.com/47158854/219026948-87b70b6f-9acd-40e3-a7b5-e7e4149d6a53.png)

### What should happen?

please help me to check.

### Capsule Farmer Version

V1.3

### Operating System

Windows 10

### Operating System Version

windows10

### Relevant log output

```shell
2023-02-10 19:41:15,824 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "FarmThread.py", line 41, in run
  File "Browser.py", line 172, in sendWatchToLive
  File "Browser.py", line 221, in __sendWatch
Exceptions.StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-10 19:41:15,825 WARNING: Thread accountname has finished.
2023-02-10 20:06:44,155 ERROR: Login for accountname FAILED!
2023-02-10 20:06:44,157 WARNING: Thread accountname has finished.
2023-02-10 20:06:54,936 ERROR: Login for accountname FAILED!
2023-02-10 20:06:54,938 WARNING: Thread accountname has finished.
2023-02-10 20:07:07,888 ERROR: Login for accountname FAILED!
2023-02-10 20:07:07,890 WARNING: Thread accountname has finished.
2023-02-10 20:07:27,354 ERROR: Login for accountname FAILED!
2023-02-10 20:07:27,355 WARNING: Thread accountname has finished.
2023-02-10 20:09:06,975 ERROR: Login for accountname FAILED!
2023-02-10 20:09:06,976 WARNING: Thread accountname has finished.
2023-02-10 20:10:10,517 ERROR: Login for accountname FAILED!
2023-02-10 20:10:10,519 WARNING: Thread accountname has finished.
2023-02-10 20:10:30,003 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "cloudscraper\__init__.py", line 98, in wrap_socket
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='auth.riotgames.com', port=443): Max retries exceeded with url: /authorize?client_id=rso-web-client-prod&redirect_uri=https%3A%2F%2Flogin.leagueoflegends.com%2Foauth2-callback&scope=openid&response_type=code&state=CEoxTrAxCUOsJZArO3TKTPsMc2gQHaBYuzl0JRM3dng&ui_locales=en (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FarmThread.py", line 35, in run
  File "Browser.py", line 51, in login
  File "requests\sessions.py", line 600, in get
  File "cloudscraper\__init__.py", line 257, in request
  File "cloudscraper\__init__.py", line 190, in perform_request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 723, in send
  File "requests\sessions.py", line 723, in <listcomp>
  File "requests\sessions.py", line 266, in resolve_redirects
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.riotgames.com', port=443): Max retries exceeded with url: /authorize?client_id=rso-web-client-prod&redirect_uri=https%3A%2F%2Flogin.leagueoflegends.com%2Foauth2-callback&scope=openid&response_type=code&state=CEoxTrAxCUOsJZArO3TKTPsMc2gQHaBYuzl0JRM3dng&ui_locales=en (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
2023-02-10 20:10:30,004 WARNING: Thread accountname has finished.
2023-02-10 20:10:45,312 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "cloudscraper\__init__.py", line 98, in wrap_socket
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.riotgames.com', port=443): Max retries exceeded with url: /sso/login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FarmThread.py", line 35, in run
  File "Browser.py", line 83, in login
  File "requests\sessions.py", line 635, in post
  File "cloudscraper\__init__.py", line 257, in request
  File "cloudscraper\__init__.py", line 190, in perform_request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.riotgames.com', port=443): Max retries exceeded with url: /sso/login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
2023-02-10 20:10:45,314 WARNING: Thread accountname has finished.
2023-02-10 20:11:05,787 ERROR: Login for accountname FAILED!
2023-02-10 20:11:05,789 WARNING: Thread accountname has finished.
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Your VPN is blocked by Riot. Read the FAQ in the Wiki.
