### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 6darkvan9** [LeagueOfPoro/CapsuleFarmerEvolved#157]
### What happened?

![image](https://user-images.githubusercontent.com/104005295/219654539-52619a2e-e89b-4f5b-ae63-e60b45f803c2.png)

It is stuck in this interface and cannot be used

### What should happen?

I hope someone will tell me how to solve this problem

### Capsule Farmer Version

Each version

### Operating System

Windows 10

### Operating System Version

win10

### Relevant log output

```shell
2023-02-17 20:20:52,387 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "cloudscraper\__init__.py", line 98, in wrap_socket
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 770, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 389, in _make_request
  File "urllib3\connectionpool.py", line 340, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FarmThread.py", line 38, in run
  File "Browser.py", line 54, in login
  File "requests\sessions.py", line 600, in get
  File "cloudscraper\__init__.py", line 257, in request
  File "cloudscraper\__init__.py", line 190, in perform_request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 578, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Read timed out. (read timeout=None)
2023-02-17 20:20:52,392 WARNING: Thread accountname has finished and will restart at 20:20:52. Number of consecutively failed logins: 0
2023-02-17 20:21:34,533 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000183E42B56C0>, 'Connection to login.leagueoflegends.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Max retries exceeded with url: /?redirect_uri=https://lolesports.com/&lang=en (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000183E42B56C0>, 'Connection to login.leagueoflegends.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FarmThread.py", line 38, in run
  File "Browser.py", line 54, in login
  File "requests\sessions.py", line 600, in get
  File "cloudscraper\__init__.py", line 257, in request
  File "cloudscraper\__init__.py", line 190, in perform_request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 553, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Max retries exceeded with url: /?redirect_uri=https://lolesports.com/&lang=en (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000183E42B56C0>, 'Connection to login.leagueoflegends.com timed out. (connect timeout=None)'))
2023-02-17 20:21:34,537 WARNING: Thread accountname has finished and will restart at 20:21:34. Number of consecutively failed logins: 0
2023-02-17 20:22:14,586 ERROR: Error in accountname. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "cloudscraper\__init__.py", line 98, in wrap_socket
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 770, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 389, in _make_request
  File "urllib3\connectionpool.py", line 340, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FarmThread.py", line 38, in run
  File "Browser.py", line 54, in login
  File "requests\sessions.py", line 600, in get
  File "cloudscraper\__init__.py", line 257, in request
  File "cloudscraper\__init__.py", line 190, in perform_request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 578, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='login.leagueoflegends.com', port=443): Read timed out. (read timeout=None)
2023-02-17 20:22:14,591 WARNING: Thread accountname has finished and will restart at 20:22:14. Number of consecutively failed logins: 0
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Read the FAQ.
