### ISSUE TITLE
[Bug]: Error status.

### ISSUE THREAD

**Issue by Newtjam** [LeagueOfPoro/CapsuleFarmerEvolved#183]
### What happened?

![image_2023-02-26_195529782](https://user-images.githubusercontent.com/25538399/221470738-16b6bcfa-5155-446d-b0c2-6ffb3cca5db9.png)
I closed the file yesterday after letting it farm, turned my pc off, got home today, turned on my pc, and any time i open the exe, i get this error. I have not touched or changed anything from before.

### What should happen?

The typical thing that happens is i open the exe, it logs in, then farms unrestricted, but instead i have an error

### Capsule Farmer Version

v1.4

### Operating System

Windows 10

### Operating System Version

Windows 10 v.22H2 Build 19045.2604

### Relevant log output

```shell
2023-02-14 06:56:05,604 ERROR: Error in Newtjam. The program will try to recover.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by Newtjam** [comment]
Turns out if this issue occurs, just closing and reopening the exe continuously after letting it attempt to login will fix it? Its working now after multiple open close attempts.
