### ISSUE TITLE
[Bug]: The Linux installation script under Ubuntu reports an error

### ISSUE THREAD

**Issue by suyi1117** [LeagueOfPoro/CapsuleFarmerEvolved#190]
### What happened?

Traceback (most recent call last):
  File "/root/CapsuleFarmerEvolved/./src/main.py", line 1, in <module>
    from DataProviderThread import DataProviderThread
  File "/root/CapsuleFarmerEvolved/src/DataProviderThread.py", line 4, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

### What should happen?

Request an answer to resolve

### Capsule Farmer Version

v1.4

### Operating System

Other (Non Windows are not natively supported)

### Operating System Version

Linux version 5.15.0-1029-oracle (buildd@bos01-arm64-023) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #35~20.04.1-Ubuntu SMP Wed Jan 25 10:16:03 UTC 2023
Python  3.10

### Relevant log output

```shell
Traceback (most recent call last):
  File "/root/CapsuleFarmerEvolved/./src/main.py", line 1, in <module>
    from DataProviderThread import DataProviderThread
  File "/root/CapsuleFarmerEvolved/src/DataProviderThread.py", line 4, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by XOYZ69** [comment]
As the error message says you need to install the missing modules. There are 2 ways of running the script.
- The first is via pyenv so that all dependencies will be automatically installed
- And the second one is to install the modules one by one (that's wat I do)

So if the Error `ModuleNotFoundError: No module named 'cloudscraper'` happens u just need to install the missing module:
- `pip3 install cloudscraper`

It is either pip or pip3 depending on your installation and configuration.

**Comment by realshiyu** [comment]
I also ran into this problem with centos7.
What I got wrong is python‘s version.My server has installed python2.7 and python3.6.
I installed python3.11 by source code and **configured the python_path**.And then the problem was resolved. 
Hope it helps.

**Comment by suyi1117** [comment]
tks! QAQ
