### ISSUE TITLE
The farmer just keep going to login

### ISSUE THREAD

**Issue by Magixian1** [LeagueOfPoro/CapsuleFarmerEvolved#34]
Once i Log inside the farmer it'll jump to Login and then LIVE status, after a while like 2-3 mins it goes again into login status and keep Looping I looked at the log and it spat out these continuesly

2023-02-03 19:44:28,489 WARNING: Thread Magixian has finished.
2023-02-03 19:44:37,854 ERROR: Error in Magixian. The program will try to recover.
Traceback (most recent call last):
  File "FarmThread.py", line 40, in run
  File "Browser.py", line 177, in sendWatchToLive
  File "Browser.py", line 215, in __sendWatch
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-03 19:44:37,854 WARNING: Thread Magixian has finished.
2023-02-03 19:44:47,466 ERROR: Error in Magixian. The program will try to recover.
Traceback (most recent call last):
  File "FarmThread.py", line 40, in run
  File "Browser.py", line 177, in sendWatchToLive
  File "Browser.py", line 215, in __sendWatch
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-03 19:44:47,467 WARNING: Thread Magixian has finished.

**Comment by Magixian1** [comment]
ok found out the API was overloaded sorry

**Comment by Korelis44** [comment]
2023-02-07 17:58:20,908 ERROR: Error in Korelis. The program will try to recover.
Traceback (most recent call last):
  File "FarmThread.py", line 41, in run
  File "Browser.py", line 172, in sendWatchToLive
  File "Browser.py", line 221, in __sendWatch
(looks like this)

**Comment by Magixian1** [comment]
i just waited around it seemed that the Riot server was overloaded with all the requests that it had, like a ddos attack, so they just trying to fix it. for now it works, if not just wait around a bit and it may work again

**Comment by Korelis44** [comment]
ok
