### ISSUE TITLE
[Bug] Has to be manually restarted every few hours

### ISSUE THREAD

**Issue by TheFeelTrain** [LeagueOfPoro/CapsuleFarmerEvolved#50]
### What happened?

After a few hours it seems like you get locked out (403) and then the script doesn't know how to handle it. My uneducated guess is that it's a token that expires. I thought it might be rate-limiting but I'm only using a single account and it happens even if there's only a couple of matches going so that seems doubtful. From the logs it looks like it attempts to resend the request but just fails over and over for about 10 minutes until eventually it can't even log back in. 

This happens a couple of times per day. A simple workaround might be to just restart the whole thing automatically if a 403 is detected since manually restarting fixes it.

### What should happen?

Keeps working indefinitely.

### Capsule Farmer Version

1.1

### Operating System

Other (Non Windows are not natively supported)

### Operating System Version

Arch Linux 
Kernel 6.1.7-zen1-1-zen
Python 3.10.9

Running with `pipenv run python ./main.py`
If it's not happening with the release binary I guess it could be something on my end. But it appears to be networking related rather than anything on my machine.

### Relevant log output

```shell
2023-02-04 03:35:18,618 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:18,619 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:22,961 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:22,961 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:26,498 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:26,498 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:30,871 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:30,871 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:36,044 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:36,044 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:43,338 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:43,338 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:35:51,427 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:35:51,427 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:36:02,176 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:36:02,176 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:36:14,407 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:36:14,407 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:36:27,336 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:36:27,336 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:36:40,765 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:36:40,765 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:36:53,791 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:36:53,791 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:37:06,974 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:37:06,974 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:37:20,565 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:37:20,566 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:37:33,138 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:37:33,138 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:37:45,243 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:37:45,243 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:37:58,575 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:37:58,575 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:38:11,538 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:38:11,538 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:38:24,802 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:38:24,802 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:38:37,838 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:38:37,838 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:38:50,797 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:38:50,797 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:39:03,492 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:39:03,492 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:39:15,729 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:39:15,729 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:39:28,489 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:39:28,489 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:39:41,460 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:39:41,460 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:39:54,180 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:39:54,180 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:40:07,599 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:40:07,599 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:42:22,544 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:42:22,545 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:42:30,257 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:42:30,257 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:42:43,377 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:42:43,377 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:42:55,492 ERROR: Error in thefeeltrain. The program will try to recover.
Traceback (most recent call last):
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/FarmThread.py", line 40, in run
    dropsAvailable = self.browser.sendWatchToLive()
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 177, in sendWatchToLive
    res = self.__sendWatch(self.liveMatches[tid])
  File "/mnt/Blue/Linux/git/CapsuleFarmerEvolved/Browser.py", line 215, in __sendWatch
    raise StatusCodeAssertException(201, res.status_code, res.request.url)
StatusCodeAssertException.StatusCodeAssertException: Received unexpected status code. Wanted 201 but got 403 in https://rex.rewards.lolesports.com/v1/events/watch
2023-02-04 03:42:55,492 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:43:13,707 ERROR: Login for thefeeltrain FAILED!
2023-02-04 03:43:13,707 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:43:28,431 ERROR: Login for thefeeltrain FAILED!
2023-02-04 03:43:28,431 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:43:41,136 ERROR: Login for thefeeltrain FAILED!
2023-02-04 03:43:41,136 WARNING: Thread thefeeltrain has finished.
2023-02-04 03:43:41,136 ERROR: Maximum login retries reached for account thefeeltrain
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by RwbyChan** [comment]
Can confirm this issue is happening here too.
Additional information:
I'm running the .exe file from version 1.1 on Windows Server 2019 (x64).
I noticed that the previous version I was using was up for +24h while the most recent I had to restart as I noticed a couple of times already that the program wasn't opened anymore.

I'm using multiple accounts. The logs seem to be similar to @TheFeelTrain where suddenly `https://rex.rewards.lolesports.com/v1/events/watch` returns 403 for a while till eventually it stops with maximum login retries reached.

**Comment by DjordyKoert** [comment]
> Can confirm this issue is happening here too. Additional information: I'm running the .exe file from version 1.1 on Windows Server 2019 (x64). I noticed that the previous version I was using was up for +24h while the most recent I had to restart as I noticed a couple of times already that the program wasn't opened anymore.
> 
> I'm using multiple accounts. The logs seem to be similar to @TheFeelTrain where suddenly `https://rex.rewards.lolesports.com/v1/events/watch` returns 403 for a while till eventually it stops with maximum login retries reached.

https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/52 should make it more obvious that you have been rate limited

**Comment by Penguax** [comment]
Temporary work around is on the discord, search for ` Automatic Restart .bat `
The script file restart the program if it hard crashes. in #capsule-farmer-help

**Comment by TheFeelTrain** [comment]
This is still happening as of the latest commit so I'm not sure why it was closed.
